"""remove title from bookings

Revision ID: 9cdb8f665736
Revises: 93993f4c953f
Create Date: 2026-10-05 13:45:22.767537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9cdb8f665736"
down_revision: Union[str, Sequence[str], None] = "93993f4c953f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
